language: node_js

sudo: false
dist: trusty

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true
    - GK_LOCK_YARN_OPTS='--ignore-engines'
    - secure: "JjOUUDTlQ+E17mLZ35qXhwrYGQHWp2BMZi+xzHMjvlu5niwCo9bfBzk9AQiheyNCL1aBUhbH/DGIXJqYp1QBgEhkdlV97RsKsXus0bsmEaDcuuzSZRy21Z6CLsbSBrlDHNp+DS0raZBlU8MP3omPxHrzaFRbslBoYtrpVQqWWmnxwEjgIhTvmjbVP2wEE/F2IAFAqSu72mF2q4fqTrqKSmbe7k08M6j6rh/v86ocqbvPZsYpkrX5tOaOf6YmtUSCR1yMcGwQHGwh4UrA5W9+1xcO7ZISuAqUgI4sWwmsKjBjfud/BAH32KURSsC/btNoedR4nKmDo8ltBy06D/NziX8gsHjKHrU1+wqGL+xAmGKpuVOr4biRMZA84+BCCVkVwl0cGzjv7Zs5IkfRP2qCf1lk04VXHAwMJGwd/qpCDImHNVMkPn6x62xI9tuoZlt2XQ/UYMzXnEOk8li5xqv1ZTuP2/HrgdLqYFOFAuUFM8i2azcQ2dMwXTTH8ucFHL45fRyeJP1nHxGIy4nzjaQVbWWVlN+wFvR3Mz8AywCLDNjUZFUGENOvbE96347i4Il4WBZx8zZ7WEfpfx7AWqPHuvIj45UWrVeMnlSowQx1bxC+lIPczao3xW2j7gH0OgxCQFA00QmEwAkJhfrJVZMzXXg9d78W5q6kVigbcczOM8E="

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "test"
      if: |
        branch ~= /^develop$|^master$|^release\/.+$/ OR \
        type = pull_request OR \
        env(RESTRICT_PUSH_BUILDS) != true
      addons:
        chrome: stable
        coverity_scan:
          project:
            name: "futa-ikeda/ember-osf-web"
            description: "<Your project description here>"
            notification_email: futa.ikeda@gmail.com
            branch_pattern: coverity_scan
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn global add greenkeeper-lockfile@1
      install:
        - yarn --prefer-offline --frozen-lockfile --ignore-engines
        - greenkeeper-lockfile-update
      script:
        - yarn lint && yarn test:node-tests && yarn test:cover
      after_script:
        - greenkeeper-lockfile-upload
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

    - stage: "deploy handbook"
      if: |
        branch = develop AND \
        type != pull_request AND \
        env(DEPLOY_KEY) IS present
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - yarn --prefer-offline --frozen-lockfile --ignore-engines
      env:
        - HANDBOOK_ENABLED=1
        - MIRAGE_ENABLED=1
        - SHOW_DEV_BANNER=1
        - A11Y_AUDIT=0
        - NODE_OPTIONS=--max-old-space-size=4096
        - TARGET_BRANCH=gh-pages
      script:
        - export ROOT_URL="/${TRAVIS_REPO_SLUG##*\/}/"
        - export ASSETS_PREFIX="${ROOT_URL}"
        - ember build --environment=production
        - cp dist/index.html dist/404.html
      deploy:
        provider: script
        skip-cleanup: true
        script: scripts/handbook_deploy.sh
        on:
          branch: develop
